# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Isp1ud0WPhHvKI0vYpI4ZQLbnb073yhF
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score

# --- 1. Load the Dataset ---
housing = fetch_california_housing()
df = pd.DataFrame(housing.data, columns=housing.feature_names)
df['Price'] = housing.target  # The target is the house price

# --- 2. Exploratory Data Analysis (Quick Look) ---
print("First 5 rows of the dataset:")
print(df.head())

# --- 3. Splitting Data ---
# X = Features (Income, House Age, etc.)
# y = Target (The Price)
X = df.drop('Price', axis=1)
y = df['Price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# --- 4. Building the Model ---
model = LinearRegression()
model.fit(X_train, y_train)

# --- 5. Making Predictions ---
predictions = model.predict(X_test)

# --- 6. Evaluation ---
mae = mean_absolute_error(y_test, predictions)
r2 = r2_score(y_test, predictions)

print(f"\n--- Model Performance ---")
print(f"Mean Absolute Error: {mae:.2f}")  # Lower is better
print(f"R-squared Score: {r2:.2f}")       # Closer to 1.0 is better

# --- 7. Visualization ---
plt.figure(figsize=(10, 6))
plt.scatter(y_test, predictions, alpha=0.5, color='blue')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel('Actual Price')
plt.ylabel('Predicted Price')
plt.title('Actual vs Predicted House Prices')
plt.show()
